version: "3"
services:
  postgres:
    container_name: quk_postgres
    restart: always
    image: postgres:13-alpine
    ports:
      - "5432:5432"
    environment:
      DATABASE_URL: postgres://docker:docker@docker:5432/docker
      POSTGRES_USER: docker
      POSTGRES_PASSWORD: docker
