name: CI
on: [push]
jobs:
  lhci:
    name: Lighthouse
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 10.x
        uses: actions/setup-node@v1
        with:
          node-version: 10.x
      - name: yarn install, build
        run: |
          yarn install
          yarn run build
      - name: run Lighthouse CI
        run: |
          yarn install -g @lhci/cli@0.7.x
          lhci autorun 