name: CI
on: [push]
jobs:
  lhci:
    name: Lighthouse
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 14.x
        uses: actions/setup-node@v2
        with:
          node-version: '14'
      - name: yarn install, build
        run: |
          yarn install
          yarn run build
      - name: run Lighthouse CI
        run: |
          yarn global add @lhci/cli@0.7.x
          lhci autorun 